AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: main
      Runtime: go1.x
      CodeUri: .
      Events:
        HelloWorld:
          Type: Api 
          Properties:
            Path: /hello
            Method: get

