apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-app
  labels:
    app: profile-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profile-app
  template:
    metadata:
      labels:
        app: profile-app
    spec:
      containers:
      - name: profile-app
        image: 520291287938.dkr.ecr.us-east-1.amazonaws.com/profile:latest
        ports:
        - containerPort: 8080
